### ISSUE TITLE
Prod bug: `other_parties` not defined

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-ALAffidavitOfIndigency#54]
```
The referer URL was https://apps.suffolklitlab.org/run/indigency/

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/webapp/server.py", line 6902, in index
    exec(list_collect_list + '._allow_appending()', user_dict)
  File "", line 1, in 
NameError: name 'other_parties' is not defined
```

Happened 12/31/2023, so recently. Not sure how it happened, but it seems to be an issue with the list collection screen in this interview where we get `other_parties`. Can't recreate it.

**Comment by samglover** [comment]
Since you weren't able to recreate this bug I'm tempted to close this issue, but since we're actively working on this interview maybe we'll see it again in our testing. If not, this comment will remind us we can close it.

**Comment by plocket** [comment]
It looks like the next step is to test thoroughly, either manually or by adding thorough automated tests.
